### ISSUE TITLE
Update SDK Demo App to be fully functional

### ISSUE THREAD

**Issue by lindanlee** [zcash/zcash-android-wallet-poc#18] opened 2020-02-11 15:11 UTC
The demo apps are a core part of our education and documentation efforts for the SDKs. With recent changes to the SDK the demo app is apparently broken. We should update the demo app to be fully functional.

**Comment by braddmiller** [comment] 2020-02-11 16:27
Edited ticket. Let's also talk about if we're adding functionality or just updating all of the existing demo app pieces to work with recent updates to the SDK

**Comment by braddmiller** [comment] 2020-02-11 16:52
This is a duplicate of https://github.com/zcash/zcash-android-wallet-sdk/issues/99 and is in the wrong repo. Closing

**Closed as completed by braddmiller** 2020-02-11 16:52 UTC
